[package]
name = "particles"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hypoloop = {version = "0.1.1", path = "D:/OneDrive/Code/hypoloop"}